name: tele_web_app
description: Allows communication between your bot and the Web App built in
  Flutter displayed inside Telegram.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  js: ^0.7.1

dev_dependencies:
  coverage: ^1.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
